FROM node:22-bullseye-slim
WORKDIR /workspace/subgraph

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq5 \
    python3 \
    make \
    g++ \
    git \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install

COPY . .

CMD ["sh", "-lc", "npm run codegen && npm run build"]
